server:
  port: 8787

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      global-cors:
        cors-configurations:
          '[/**]':
#            allowedOrigins: "http://localhost:8080"  # Адрес фронтенда
            allowedOrigins: "*"  # Адрес фронтенда
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
#            allowCredentials: true
      routes:
        - id: app-service
          uri: lb://app-service
          predicates:
            - Path=/api/v1/app/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/